#!/usr/bin/python
# Licensed to the StackStorm, Inc ('StackStorm') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import json

import requests

from st2client.client import Client

def get_required_key(client, key_name) :
    key = client.keys.get_by_name(key_name)

    if key is None:
        raise Exception('Required key ' + key_name + ' does not exist.')

    value = key.value
    if not value:
        raise Exception('No value for required key ' + key_name)

    return value

try:
  client = Client()
  bot_host = get_required_key(client, 'bot_host')
  bot_port = get_required_key(client, 'bot_port')
  bot_endpoint = get_required_key(client, 'bot_endpoint')
except Exception, e:
  print(e)
  sys.exit(2)

sys.argv.pop(0)

data = {}
payload = {}

payload['source'] = sys.argv[0]
sys.argv.pop(0)
payload['name'] = sys.argv[0]
sys.argv.pop(0)

args = ' '.join(map(str,sys.argv))

try:
  json.loads(args)
  payload['msg'] = args
except ValueError, e:
  payload['msg'] = json.dumps({'message': args})

url = 'http://' + bot_host + ':' + bot_port + bot_endpoint
headers = {'content-type': 'application/json'}

data['payload'] = payload
r = requests.post(url, data=json.dumps(data), headers=headers)
print(r.text)
