python_sources(
    overrides={
        "app.py": dict(
            dependencies=[
                # controller routes are wired up via st2common/st2common/openapi.yaml
                "./controllers",
                "./controllers/v1",
                # "./controllers/exp",
            ],
        ),
    },
)
