#!/bin/sh
# postinst script for st2
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

ST2_USER=st2
PACKS_GROUP=st2packs
ST2_UPGRADESTAMP="/tmp/.stamp-stackstorm-st2-deb-package"
upgrading=0

_ST2_SERVICES="
st2actionrunner.service
st2api.service
st2auth.service
st2garbagecollector.service
st2notifier.service
st2rulesengine.service
st2scheduler.service
st2sensorcontainer.service
st2stream.service
st2timersengine.service
st2workflowengine.service
"

## Permissions of files which should be set on install
SET_PERMS=$(cat <<EHD | sed 's/\s\+/ /g'
-R ug+rw root:_packsgroup /opt/stackstorm/packs
-R ug+rw root:_packsgroup /usr/share/doc/st2/examples
   ug+rw root:_packsgroup /opt/stackstorm/virtualenvs
   755 _st2user:root      /opt/stackstorm/configs
   755 _st2user:root      /opt/stackstorm/exports
   755 _st2user:root      /var/log/st2
   755 _st2user:root      /var/run/st2
   600 _st2user:_st2user  /etc/st2/htpasswd
EHD
)

## Fix directories permissions on install (different across maint scripts!)
set_permissions() {
  local fileperms="$1"
  fileperms=$(echo "$fileperms" | sed -e "s/_st2user/$ST2_USER/g" -e "s/_packsgroup/$PACKS_GROUP/g")
  # Reqursively chown given destinations!
  echo "$fileperms" | cut -f1,3,4 -d' ' | xargs -L1 chown
  # Set directories mode
  echo "$fileperms" | cut -f1,2,4 -d' ' | xargs -L1 chmod
}

# Choose first install or upgrade
[ -f $ST2_UPGRADESTAMP ] && upgrading=1 || :

case "$1" in
    configure)
      # Initially set destination files owenership (only on the first install)
      [ "$upgrading" = 1 ] || set_permissions "$SET_PERMS"
      rm -f $ST2_UPGRADESTAMP

      # make sure that our socket generators run
      systemctl daemon-reload >/dev/null 2>&1 || true
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# based on dh_systemd_enable/12.10ubuntu1 and dh_systemd_start/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    for service in ${_ST2_SERVICES}; do
        # This will only remove masks created by d-s-h on package removal.
        deb-systemd-helper unmask "${service}" >/dev/null || true

        # was-enabled defaults to true, so new installations run enable.
        if deb-systemd-helper --quiet was-enabled "${service}"; then
            # Enables the unit on first installation, creates new
            # symlinks on upgrades if the unit file has changed.
            deb-systemd-helper enable "${service}" >/dev/null || true
        else
            # Update the statefile to add new symlinks (if any), which need to be
            # cleaned up on purge. Also remove old symlinks.
            deb-systemd-helper update-state "${service}" >/dev/null || true
        fi
    done
    systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action ${_ST2_SERVICES} >/dev/null || true
fi

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.
# includes:
#   dh_python2: dh-virtualenv
#   dh_systemd_enable/12.10ubuntu1
#   dh_systemd_start/12.10ubuntu1

#DEBHELPER#



exit 0
