#!/bin/sh
# postrm script for st2
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

purge_files() {
    # This -pkgsaved.disabled file might be left over from old (buggy) deb packages
    rm -f /etc/logrotate.d/st2-pkgsaved.disabled 1>/dev/null 2>&1 || :
    # Clean up other StackStorm related configs and directories
    rm -rf /etc/st2 1>/dev/null 2>&1 || :
    rm -rf /opt/stackstorm 1>/dev/null 2>&1 || :
    rm -rf /root/.st2 1>/dev/null 2>&1 || :
    rm -rf /var/log/st2 1>/dev/null 2>&1 || :
    rm -f /etc/sudoers.d/st2 1>/dev/null 2>&1 || :
}

case "$1" in
    purge)
        purge_files
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
