#!/bin/sh
# postrm script for st2
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#     <postrm> remove
#         on remove or remove+purge
#     <postrm> purge
#         on purge or remove+purge
#     <old-postrm> upgrade <new-version>
#         on upgrade
#     <disappearer's-postrm> disappear <overwriter> <overwriter-version>
#         on implicit removal (all package files replaced by another package)
#     <new-postrm> abort-install
#         on failed fresh install (after <preinst> failed)
#     <new-postrm> abort-install <old-version> <new-version>
#         on failed install after pkg removal w/o conf purge (and <preinst> failed)
#     <new-postrm> failed-upgrade <old-version> <new-version>
#         on upgrade failed (after <old-postrm> failed)
#     <new-postrm> abort-upgrade <old-version> <new-version>
#         on upgrade failed (after <new-preinst> or <old-postrm> failed)
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html

purge_files() {
    # This -pkgsaved.disabled file might be left over from old (buggy) deb packages
    rm -f /etc/logrotate.d/st2-pkgsaved.disabled 1>/dev/null 2>&1 || :
    # Clean up other StackStorm related configs and directories
    rm -rf /etc/st2 1>/dev/null 2>&1 || :
    rm -rf /opt/stackstorm 1>/dev/null 2>&1 || :
    rm -rf /root/.st2 1>/dev/null 2>&1 || :
    rm -rf /var/log/st2 1>/dev/null 2>&1 || :
    rm -f /etc/sudoers.d/st2 1>/dev/null 2>&1 || :
}

case "$1" in
    purge)
        purge_files
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
