checks:
  tags:
    - el8
  stage: checks
  variables:
    GITLAB_TOKEN_U: ORCHESTRATION_GAT
    GITLAB_TOKEN_K: $ORCHESTRATION_GAT_READ_2
    PYTHON_VERSION: python3.11
  before_script:
    - yum --enablerepo epel install -y ShellCheck
    - yum --enablerepo rocky8_app_stream install -y python3.11-devel
    - yum --enablerepo rocky8_base_os install -y openldap-devel
  script:
    - make requirements
    - make ci-checks
  rules:
    - if: '($CI_PIPELINE_SOURCE == "push")'

unittests:
  tags:
    - el8
  stage: unittests
  variables:
    GITLAB_TOKEN_U: ORCHESTRATION_GAT
    GITLAB_TOKEN_K: $ORCHESTRATION_GAT_READ_2
    FF_NETWORK_PER_BUILD: 1
    ST2_OVERRIDE_HOST: mymongo
    # tests actually expect coordinator to be off
    ST2_TESTS_REDIS_HOST: redis
    ST2_DB_CONNECTION_TIMEOUT: 60000 # milliseconds
    ST2_MESSAGING_HOST: rabbitmq
    DOCKER_DRIVER: overlay2
    CONTENT_FOLDER: st2tests/st2tests/fixtures/packs/test_content_version
    PYTHON_VERSION: python3.11

  services:
    - name: harbor.global.lmco.com/ext.hub.docker.com/mongo:7.0.21
      alias: mymongo
    - name: registry.ifp.lmco.com/redis:6.0
      alias: redis
    - name: registry.ifp.lmco.com/rabbitmq:3.6-management
      alias: rabbitmq


  before_script:
    - git clone https://$GITLAB_TOKEN_U:$GITLAB_TOKEN_K@gitlab.ifp.lmco.com/orchestration/stackstorm/stackstorm-test-content-version  $CONTENT_FOLDER
    - yum --enablerepo lmprod install -y sudo mongodb-org-shell bind-utils
    - yum --enablerepo rocky8_app_stream install -y python3.11-devel
    - yum --enablerepo rocky8_base_os install -y openldap-devel
    - time mongo mymongo/admin
    - useradd stanley
    - time nslookup mymongo

  script:
    - export ST2_OVERRIDE_HOST=$(dig +short mymongo | head -n1)
    - echo $ST2_OVERRIDE_HOST
    - make unit-tests

  rules:
    - if: '($CI_PIPELINE_SOURCE == "push")'


stages:
  - checks
  - unittests
