python_sources(
    overrides={
        "root.py": dict(
            dependencies=[
                "st2api/st2api/public",  # cfg.static_root (has logo images)
                "st2api/st2api/templates",  # cfg.template_path
            ],
        ),
    },
)
