__all__ = [
    'ACTION_NAME',
    'ACTION_ID',

    'LIBS_DIR',

    'ACTIONEXEC_STATUS_SCHEDULED',
    'ACTIONEXEC_STATUS_RUNNING',
    'ACTIONEXEC_STATUS_SUCCEEDED',
    'ACTIONEXEC_STATUS_FAILED',

    'ACTIONEXEC_STATUSES'
]


ACTION_NAME = 'name'
ACTION_ID = 'id'
ACTION_PACK = 'pack'

LIBS_DIR = 'lib'

ACTIONEXEC_STATUS_SCHEDULED = 'scheduled'
ACTIONEXEC_STATUS_RUNNING = 'running'
ACTIONEXEC_STATUS_SUCCEEDED = 'succeeded'
ACTIONEXEC_STATUS_FAILED = 'failed'

ACTIONEXEC_STATUSES = [ACTIONEXEC_STATUS_SCHEDULED,
                       ACTIONEXEC_STATUS_RUNNING, ACTIONEXEC_STATUS_SUCCEEDED,
                       ACTIONEXEC_STATUS_FAILED]
