st2_logging_conf_file(
    name="logging_console",
    source="console.conf",
)

st2_logging_conf_file(
    name="logging",
    source="logging.conf",
)

st2_logging_conf_file(
    name="logging_gunicorn",
    source="logging.gunicorn.conf",
)

st2_logging_conf_file(
    name="logging_syslog",
    source="syslog.conf",
)
