st2_runner_python_distribution(
    runner_name="noop",
    description=(
        "No-Op action runner for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "noop": "noop_runner.noop_runner",
        },
    },
)
