st2_runner_python_distribution(
    runner_name="inquirer",
    description=(
        "Inquirer action runner for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "inquirer": "inquirer_runner.inquirer_runner",
        },
    },
)
