#!/bin/bash

set -e

mkdir -p /var/log/st2
mkdir -p /etc/st2
mkdir -p /opt/stackstorm/packs
mkdir -p /opt/stackstorm/rbac
mkdir -p /opt/stackstorm/rbac/roles
mkdir -p /opt/stackstorm/rbac/assignments
