python_sources(
    overrides={
        "__init__.py": dict(
            dependencies=[
                # Public API classes that cannot be inferred
                "./base.py",
            ],
        ),
    },
)
