__dependencies_rules__(
    # st2common.services.inquiry may depend on st2actions.container.base
    # TODO: Refactor so st2common does not import st2actions any more.
    ("/inquiry.py", "//st2actions/st2actions/container/base.py"),
    # fall back to rules defined in parent directories
    extend=True,
)

python_sources()
