resources(
    name="assets",
    sources=[
        "**/*.cer",
        "**/*.cnf",
        "**/*.p12",
        "**/*.pem",
        "ca/index.txt*",
        "ca/serial*",
    ],
)

python_sources(
    dependencies=[":assets"],
)
