import mongoengine as me


class StormFoundationDB(me.Document):
    """Absolute minimal representation of a model entity. This foundation
       class should only be directly inherited from for system-created objects.
       Attribute:
           uri : the uri for the entity.
           id : unique identifer for the entity. (UUID)
    """
    # ObjectIdField should be not have any constraints like required,
    # unique etc for it to be auto-generated.
    # TODO: Work out how we can mark this as a unique primary key.
    id = me.ObjectIdField()
    # see http://docs.mongoengine.org/guide/defining-documents.html#
    # abstract-classes

    uri = me.fields.URLField()
    meta = {
        'abstract': True
    }


class StormBaseDB(StormFoundationDB):
    """Minimal representation of a model entity where the entity is created by users.
    Attribute:
        uri : uri of the entity.
        name : name of the entity.
        description : description of the entity.
        id : unique identifier for the entity. If none is provided it
        will be auto generated by the system.
    """
    name = me.StringField(required=True)
    description = me.StringField()
    # see http://docs.mongoengine.org/guide/defining-documents.html#
    # abstract-classes
    meta = {
        'abstract': True
    }
