import mongoengine as me


class BaseDB(me.Document):
    """Minimal representation a model entity.
    Attribute:
        uri : uri of the entity.
        name : name of the entity.
        description : description of the entity.
        id : unique identifier for the entity. If none is provided it
        will be auto generated by the system.
    """
    uri = me.fields.URLField()
    name = me.StringField(required=True)
    description = me.StringField()
    # ObjectIdField should be not have any constraints like required,
    # unique etc for it to be auto-generated.
    # TODO: Work out how we can mark this as a unique primary key.
    id = me.ObjectIdField()
    # see http://docs.mongoengine.org/guide/defining-documents.html#
    # abstract-classes
    meta = {
        'abstract': True
    }
