import mongoengine as me


class BaseDB(me.Document):
    """Minimal representation a model entity.
    Attribute:
        name : name of the entity.
        description : description of the entity.
        id : unique identifier for the entity. If none is provided it
        will be auto generated by the system.
    """
    name = me.StringField(required=True)
    description = me.StringField()
    # ObjectIdField should be not have any constraints like required,
    # unique etc for it to be auto-generated.
    id = me.ObjectIdField()
    # see http://docs.mongoengine.org/guide/defining-documents.html#
    # abstract-classes
    meta = {
        'abstract': True
    }
