pack_metadata(
    name="metadata",
)

python_sources(
    dependencies=[
        ":metadata",
        "./actions",
        "./sensors",
        "st2tests/st2tests/fixtures/packs/configs/dummy_pack_1.yaml",
    ],
)
