shell_sources(
    overrides={
        (
            "add-itest-user-key.sh",
            "permissions-workaround.sh",
            "run-nightly-make-task-if-exists.sh",
            "submit-codecov-coverage.sh",
            "time-command.sh",
        ): dict(skip_shfmt=True),
    },
)
