st2_component_python_distribution(
    component_name="st2tests",
    dependencies=[
        "./st2tests/policies",
        "./st2tests/policies/meta",
        "./st2tests/mocks",
        "./st2tests/mocks/runners",
        # fixture packs
        "./st2tests/fixtures/generic",
        "./st2tests/fixtures/localrunner_pack",
        "./st2tests/fixtures/packs:all_packs",
        "./st2tests/fixtures/packs_1:all_packs",
        "./st2tests/fixtures/packs_invalid:all_packs",
        # fixtures in packs that are not (directly) packs
        "./st2tests/fixtures/packs/executions",
        "./st2tests/fixtures/packs/runners",
        "./st2tests/fixtures/packs/test_content_version_fixture",  # provides fixture const
        # fixture db resources (eg yaml dump of db resources)
        "./st2tests/fixtures/aliases",
        "./st2tests/fixtures/backstop",
        "./st2tests/fixtures/descendants",
        "./st2tests/fixtures:rbac_fixtures",
        "./st2tests/fixtures/rule_enforcements",
        "./st2tests/fixtures/timers",
        "./st2tests/fixtures/traces",
        # fixture etc
        "./st2tests/fixtures/conf",
        "./st2tests/fixtures/history_views",
        "./st2tests/fixtures/keyczar_keys",
        "./st2tests/fixtures/specs",
        "./st2tests/fixtures/ssl_certs",
    ],
)
