st2_runner_python_distribution(
    runner_name="remote",
    description=(
        "Remote SSH shell command and script action runner "
        "for the StackStorm event-driven automation platform"
    ),
)
