file(
    name="st2.conf",
    source="st2.conf",
)

file(
    name="st2_kvstore_tests.crypto.key.json",
    source="st2_kvstore_tests.crypto.key.json",
)

st2_logging_conf_file(
    name="logging.conf",
    source="logging.conf",
)

st2_logging_conf_files(
    name="other_logging_conf",
    sources=["logging.*.conf"],
)

file(
    name="vagrant_ssh_key",
    source="vagrant.privkey.insecure",
)
