files(
    name="st2.conf",
    sources=["st2.conf"],
)

files(
    name="st2_kvstore_tests.crypto.key.json",
    sources=["st2_kvstore_tests.crypto.key.json"],
)

files(
    name="logging.conf",
    sources=["logging.conf"],
)

files(
    name="other-logging-conf",
    sources=["logging.*.conf"],
)
