st2_component_python_distribution(
    component_name="st2actions",
    scripts=[
        "bin/st2actionrunner",
        "bin/st2notifier",
        "bin/st2workflowengine",
        "bin/st2scheduler",
        "bin/runners.sh:shell",  # used by service files installed by st2-packaging
    ],
)
