python_tests(
    name="tests",
    overrides={
        "test_v35_migrate_db_dict_field_values.py": dict(
            dependencies=[
                "st2common/bin/migrations/v3.5/st2_migrate_db_dict_field_values.py",
            ],
        ),
    },
)
