python_sources(
    overrides={
        "process_container.py": dict(
            dependencies=[
                # This is called in a subprocess using filesystem path
                "./sensor_wrapper.py",
            ],
        ),
    },
)
