file(
    name="logging_console",
    source="console.conf",
)

file(
    name="logging",
    source="logging.conf",
)

file(
    name="logging_gunicorn",
    source="logging.gunicorn.conf",
)

file(
    name="logging_syslog",
    source="syslog.conf",
)
