st2_runner_python_distribution(
    runner_name="http",
    description=(
        "HTTP(s) action runner for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "http-request": "http_runner.http_runner",
        },
    },
)
