st2_runner_python_distribution(
    runner_name="announcement",
    description=(
        "Announcement action runner "
        "for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "announcement": "announcement_runner.announcement_runner",
        },
    },
)
