st2_runner_python_distribution(
    runner_name="local",
    description=(
        "Local Shell Command and Script action runner "
        "for the StackStorm event-driven automation platform"
    ),
)
