#!/bin/bash

PACK="tests"
USRPATH="/usr/share/stackstorm"
TESTSPATH="/opt/stackstorm/tests/packs"

if [ -d ${USRPATH}/${PACK} ]; then
    mkdir -p ${TESTSPATH}
    cp -Rf ${USRPATH}/${PACK} ${TESTSPATH}
else
    echo "${PACK} does not exist in ${USRPATH}"
    exit 2
fi

echo -e "Adding packs_base_paths for ${TESTSPATH}..."
grep packs_base_path /etc/st2/st2.conf || echo -e "\n[content]\npacks_base_paths = ${TESTSPATH}" >> /etc/st2/st2.conf

if [[ $? -ne 0 ]]; then
    echo "Failed to add pack path!"
    exit 2
else
    echo -e "Restarting St2 for new path to take affect..."
    st2ctl restart
    echo -e "Reloading St2 content..."
    st2ctl reload
fi

if [ -f ${TESTSPATH}/${PACK}/requirements.txt ]; then
    echo "Creating virtualenv for ${PACK}..."
    mkdir -p /opt/stackstorm/virtualenvs
    virtualenv --system-site-packages /opt/stackstorm/virtualenvs/${PACK}
    echo "Installing requirements.txt for ${PACK}..."
    pip install -r ${TESTSPATH}/${PACK}/requirements.txt -E /opt/stackstorm/virtualenvs/${PACK}
fi
