#!/bin/bash
LOGFILE="/tmp/st2_startup.log"
COMPONENTS="actionrunner st2api sensor_container history rules_engine mistral"
STANCONF="/etc/st2/st2.conf"
PYTHON=`which python`
if [ -z "$AR" ];
 then
   AR=10
fi

DEBTEST=`lsb_release -a 2> /dev/null | grep Distributor | awk '{print $3}'`

if [[ "$DEBTEST" == "Ubuntu" ]]; then
  TYPE="debs"
  PYTHONPACK="/usr/lib/python2.7/dist-packages"
elif [[ -f "/etc/redhat-release" ]]; then
  TYPE="rpms"
  PYTHONPACK="/usr/lib/python2.7/site-packages"
else
  echo "Unknown Operating System"
  exit 2
fi

function st2start(){
  for i in `seq 1 ${AR}`
  do
    nohup actionrunner --config-file ${STANCONF} &>> ${LOGFILE} &
  done
  nohup st2api --config-file ${STANCONF} &>> ${LOGFILE} &
  nohup sensor_container --config-file ${STANCONF} &>> ${LOGFILE} &
  nohup /usr/bin/history --config-file ${STANCONF} &>> ${LOGFILE} &
  nohup rules_engine --config-file ${STANCONF} &>> ${LOGFILE} &
  if [[ "${CONTAINER}" == "DOCKER" ]]
  then
    /opt/openstack/mistral/.venv/bin/python /opt/openstack/mistral/mistral/cmd/launch.py --config-file /etc/mistral/mistral.conf --log-file /var/log/mistral.log &> /dev/null &
  else
    service mistral start
  fi
}

function st2stop(){
  for COM in $COMPONENTS
  do
    if [[ "${COM}" == "mistral" ]]
    then
      PID=`ps ax | grep -v grep | grep ${COM} | awk '{print $1}'`
      if [[ ! -z $PID ]]
      then
        for p in $PID
        do
           echo "Killing ${COM} PID: ${p}"
        done
        if [[ "${CONTAINER}" == "DOCKER" ]]
        then
          kill $p
        else
          service mistral stop
        fi
      else
        echo "${COM} is not running"
      fi
    else
      PID=`ps ax | grep -v grep | grep ${COM} | awk '{print $1}'`
      if [[ ! -z $PID ]]
      then
        for p in $PID
        do
          echo "Killing ${COM} PID: ${p}"
          kill $p
        done
      else
        echo "${COM} is not running"
      fi
    fi
  done
}

function restart_component() {
  COM=${1}
  if [[ ! -z $COM ]]
  then
    if [[ "${COM}" == "actionrunner" ]]
    then
      PROC_COUNT=${AR}
    else
      PROC_COUNT=1
    fi
    echo "restarting service ${COM} with ${PROC_COUNT} process(es)."
    if [[ "${COM}" == "mistral" ]]
    then
      if [[ "${CONTAINER}" == "DOCKER" ]]
      then
        kill $p
        sleep 1
        /opt/openstack/mistral/.venv/bin/python /opt/openstack/mistral/mistral/cmd/launch.py --config-file /etc/mistral/mistral.conf --log-file /var/log/mistral.log &> /dev/null &
      else
        service mistral restart
      fi
    else
      PID=`ps ax | grep -v grep | grep -v st2ctl | grep ${COM} | awk '{print $1}'`
      if [[ ! -z $PID ]]
      then
        for p in $PID
        do
          echo "Killing ${COM} PID: ${p}"
          kill $p
        done
        for i in `seq 1 ${PROC_COUNT}`
        do
          ${COM} --config-file ${STANCONF} &>> ${LOGFILE} &
        done
      else
        echo "${COM} is not running"
      fi
    fi
  else
    echo "No component specified to restart."
  fi
}

function register_content() {
  echo "Registering content..."
  $PYTHON ${PYTHONPACK}/st2common/bin/registercontent.py --config-file ${STANCONF} ${1}
}

clean_db() {
  echo "Dropping Database..."
  mongo st2 --eval "db.dropDatabase();"
}

clean_logs() {
  echo "Cleaning Logs..."
  rm -Rf /var/log/st2/*
}

function getpids(){
  for COM in $COMPONENTS
  do
    PID=`ps ax | grep -v grep | grep -v st2ctl | grep "${COM}" | awk '{print $1}'`
    if [[ ! -z $PID ]]
    then
      for p in $PID
      do
        echo "${COM} PID: ${p}"
      done
    else
      echo "${COM} is not running"
    fi
  done
}

case ${1} in
  start)
    st2start
    getpids
    ;;
  stop)
    st2stop
    ;;
  restart)
    st2stop
    sleep 1
    st2start
    getpids
    ;;
  restart-component)
    restart_component ${2}
    sleep 1
    getpids
    ;;
  reload)
    register_content ${2}
    getpids
    ;;
  clean)
    echo "This will drop the database and delete all logs.  Are you sure [y/n]?"
    read verify
    if [[ "$verify" == "y" ]]; then
      st2stop
      clean_db
      clean_logs
      register_content ${2}
      st2start
      getpids
    else
      exit
    fi
    ;;
  status)
    getpids
    ;;
  *)
    echo "Valid actions: start|stop|restart|restart-component|reload|clean|status"
    ;;
esac
