#!/usr/bin/env python
# Licensed to the StackStorm, Inc ('StackStorm') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Script which submits per StackStorm service (process) metrics to statsd.

Metrics include:

  * CPU usage
  * Memory usage
  * IO / disks usage
"""

import sys
import socket
import logging
import argparse

import six

try:
    import psutil
except ImportError:
    msg = ('psutil library is not available you can install it using:\n'
           'pip install psutil')
    raise ImportError(msg)

try:
    import statsd
except ImportError:
    msg = ('python-statsd library is not available you can install it using:\n'
           'pip install python-statsd')
    raise ImportError(msg)


LOG = logging.getLogger(__name__)


def setup_logging():
    root = logging.getLogger()
    root.setLevel(logging.DEBUG)

    handler = logging.StreamHandler(sys.stdout)
    handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    root.addHandler(handler)


def get_stackstorm_services_pids():
    """
    Return pids for StackStorm service processes.
    """
    result = []
    for proc in psutil.process_iter():
        pinfo = proc.as_dict(attrs=['pid', 'name', 'cmdline'])

        # General stackstorm service (st2actionrunner, st2timersengine, etc)
        if pinfo['name'].startswith('st2'):
            result.append(pinfo['pid'])

        continue

    return result


def get_metrics_for_process(pid):
    """
    Return metrics for a provided process id.

    :rtype: ``dict``
    """
    p = psutil.Process(pid)

    data = {
        'name': None,
        'cpu': {
            'percentage': None,
            'system_time': None,
            'user_time': None
        },
        'memory': {
            'rss': None,
            'vms': None,
            'swap': None
        },
        'io': {
            'read_count': None,
            'write_count': None
        }
    }

    with p.oneshot():
        data['name'] = p.name()
        data['pid'] = pid

        data['cpu']['percentage'] = p.cpu_percent()

        cpu_times = p.cpu_times()
        data['cpu']['system_time'] = cpu_times.system
        data['cpu']['user_time'] = cpu_times.user

        memory_info = p.memory_full_info()
        data['memory']['rss'] = memory_info.rss
        data['memory']['vms'] = memory_info.vms
        data['memory']['swap'] = memory_info.swap

        io_counters = p.io_counters()
        data['io']['read_count'] = io_counters.read_count
        data['io']['write_count'] = io_counters.write_count

    return data

def submit_metrics_to_statsd():
    service_pids = get_stackstorm_services_pids()

    hostname = socket.gethostname()


    for service_pid in service_pids:
        metrics = get_metrics_for_process(service_pid)

        LOG.debug('Submitting metrics for process %s@%s' % (metrics['name'], hostname))

        for key in ['cpu', 'memory', 'io']:
            items = metrics[key]

            for item_name, item_value in six.iteritems(items):
                # Skip empty / invalid values:
                if not item_value or item_value == 0.0:
                    continue

                # E.g. st2.st2api.1110.cpu.percentage
                name = metrics['name']
                pid = metrics['pid']
                metric_key = '%s.%s.%s.%s.%s' % (name, hostname, pid, key,
                                                 item_name)

                gauge = statsd.Gauge(metric_key)
                gauge.send(None, item_value)


def main():
    parser = argparse.ArgumentParser(description='Script which submits per StackStorm service '
                                                 'metrics to statsd')
    parser.add_argument('--statsd-host', required=True,
                        help='Statsd hostname')
    parser.add_argument('--statsd-port', type=int, default=8125,
                        help='Statsd port')

    args = parser.parse_args()

    # Initialize statsd connection
    statsd.Connection.set_defaults(host=args.statsd_host, port=args.statsd_port)

    # Initialize logging
    setup_logging()

    # Submit metrics to statsd
    submit_metrics_to_statsd()


if __name__ == '__main__':
    main()
