python_requirement(
    name="winrm",
    requirements=["pywinrm"],
    # modules can be removed once pants is released with
    # https://github.com/pantsbuild/pants/pull/17390
    modules=["winrm"],
)

st2_runner_python_distribution(
    runner_name="winrm",
    description=(
        "WinRM shell command and PowerShell script action runner "
        "for the StackStorm event-driven automation platform"
    ),
)
