python_requirement(
    name="winrm",
    requirements=["pywinrm"],
    # modules can be removed once pants is released with
    # https://github.com/pantsbuild/pants/pull/17390
    modules=["winrm"],
)
