st2_runner_python_distribution(
    runner_name="action_chain",
    description=(
        "Action-Chain workflow action runner "
        "for the StackStorm event-driven automation platform"
    ),
)
