st2_runner_python_distribution(
    runner_name="action_chain",
    description=(
        "Action-Chain workflow action runner "
        "for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "action-chain": "action_chain_runner.action_chain_runner",
        },
    },
)
