st2_runner_python_distribution(
    runner_name="python",
    description=(
        "Python action runner for the StackStorm event-driven automation platform"
    ),
    entry_points={
        stevedore_namespace("st2common.runners.runner"): {
            "python-script": "python_runner.python_runner",
        },
    },
    zip_safe=False,
)
