python_sources(
    dependencies=[
        "st2tests/conf:st2.conf",
        "st2tests/conf:st2_kvstore_tests.crypto.key.json",
        "st2tests/conf:logging.conf",
        # These are for base.py, but do not use overrides because __init__ import base.
        "./resources:ssh",
        "./resources:packs",
    ],
)
