---
# This Lint workflow uses pants
name: Lint

on:
  push:
    branches:
      # only on merges to master branch
      - master
      # and version branches, which only include minor versions (eg: v3.4)
      - v[0-9]+.[0-9]+
    tags:
      # also version tags, which include bugfix releases (eg: v3.4.0)
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    type: [opened, reopened, edited]
    branches:
      # Only for PRs targeting those branches
      - master
      - v[0-9]+.[0-9]+
  #schedule:
  #  # run every night at midnight
  #  - cron:  '0 0 * * *'

jobs:
  # Lint checks which don't depend on any service containes, etc. to be running.
  lint-checks:
    name: 'Lint Checks (pants runs: shellcheck, bandit, black, flake8, pylint)'
    runs-on: ubuntu-20.04

    env:
      COLUMNS: '120'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # a test uses a submodule, and pants needs access to it to calculate deps.
          submodules: 'true'

      #- name: Cache APT Dependencies
      #  id: cache-apt-deps
      #  uses: actions/cache@v2
      #  with:
      #    path: |
      #      ~/apt_cache
      #    key: ${{ runner.os }}-apt-v7-${{ hashFiles('scripts/github/apt-packages.txt') }}
      #    restore-keys: |
      #      ${{ runner.os }}-apt-v7-
      - name: Install APT Depedencies
        env:
          CACHE_HIT: 'false' # cache doesn't work
          #CACHE_HIT: ${{steps.cache-apt-deps.outputs.cache-hit}}
        run: |
          # install dev dependencies for Python YAML and LDAP packages
          # https://github.com/StackStorm/st2-auth-ldap
          ./scripts/github/install-apt-packages-use-cache.sh

      - name: Initialize Pants and its GHA caches
        uses: pantsbuild/actions/init-pants@v6-scie-pants
        # This action adds an env var to make pants use both pants.ci.toml & pants.toml.
        # This action also creates 3 GHA caches (1 is optional).
        # - `pants-setup` has the bootsrapped pants install
        # - `pants-named-caches` has pip/wheel and PEX caches
        # - `pants-lmdb-store` has the fine-grained process cache.
        #   If we ever use a remote cache, then we can drop this.
        #   Otherwise, we may need an additional workflow or job to delete old caches
        #   if they are not expiring fast enough, and we hit the GHA 10GB per repo max.
        with:
          base-branch: master
          # To ignore a bad cache, bump the cache* integer.
          gha-cache-key: cache0
          # This hash should include all of our lockfiles so that the pip/pex caches
          # get invalidated on any transitive dependency update.
          named-caches-hash: ${{ hashFiles('requirements.txt') }}
          # enable the optional lmdb_store cache since we're not using remote caching.
          cache-lmdb-store: 'true'
          # install whatever version of python we need for our in-repo pants-plugins
          setup-python-for-plugins: 'true'

      - name: Lint
        run: |
          pants lint ::

      - name: Upload pants log
        uses: actions/upload-artifact@v2
        with:
          name: pants-log-py${{ matrix.python-version }}
          path: .pants.d/pants.log
        if: always()  # We want the log even on failures.
